@startuml
title Liste und zugehörige Ressourcen abrufen ($list-read)

skinparam borderColor #000000
skinparam backgroundColor #f5f5f5
skinparam shadowing false
skinparam roundCorner 10
skinparam defaultFontName "Arial"
skinparam defaultFontSize 14
skinparam defaultFontColor #000000

skinparam note {
  BackgroundColor #e0e5f0-#d1d9e6
  BorderColor #8b95a5
  BorderThickness 1
  RoundCorner 8
  Padding 6
  FontColor #111827
  Shadowing true
}

skinparam HyperlinkColor #0000EE
skinparam HyperlinkUnderline false

skinparam sequence {
  ParticipantBorderColor #555555
  ParticipantBackgroundColor #ffffff
  ParticipantFontColor #000000
  ParticipantFontSize 14
  ParticipantPadding 20
  ArrowColor #111827
  ArrowThickness 1
  ArrowFontColor #000000
  ArrowFontSize 13
  GroupBorderColor #111827
  GroupBackgroundColor #eef2ff
  GroupBorderThickness 2
}

!define COLOR_GDA_1    #0078D460
!define COLOR_GDA_2    #8764B860
!define COLOR_PATIENT  #00950560
!define COLOR_APO      #00B7C360
!define COLOR_DIAG_FA  #E9713280
!define COLOR_E_REZEPT #E7485660

!define COLOR_OK       #50E6FF25
!define COLOR_ERROR    #FF8C0035

actor GDA_1 as "GDA 1" COLOR_GDA_1
participant eDiag_FA as "e-Diagnose Fachanwendung" COLOR_DIAG_FA

autonumber

GDA_1 -> eDiag_FA: POST /[Condition|Procedure|AllergyIntolerance]/$list-read
activate GDA_1 COLOR_GDA_1
activate eDiag_FA COLOR_DIAG_FA

eDiag_FA -> eDiag_FA: Auf bestehende Liste(n) prüfen

group COLOR_OK alt: Liste(n) vorhanden? [Liste(n) vorhanden]

  eDiag_FA -> eDiag_FA: Liste mit aktuellem List.date ermitteln

  eDiag_FA -> eDiag_FA: Prüfen, ob List.emptyReason vorhanden ist
  
  group COLOR_OK alt: List.emptyReason vorhanden? [nein]

    eDiag_FA -> eDiag_FA: Flags der Listeneinträge aufbereiten\nnew|changed → unchanged\nremoved → entfernen
    eDiag_FA -> eDiag_FA: Zählen der Listeneinträge

    group COLOR_OK alt: Anzahl Einträge? [zumindest ein Eintrag]

      eDiag_FA --> GDA_1: Collection-Bundle (List mit Einträgen) +\nETag für Optimistic Locking

    else COLOR_ERROR Liste leer
      
      eDiag_FA -> eDiag_FA: List.emptyReason = nilknown setzen
      eDiag_FA --> GDA_1: Collection-Bundle (List ohne Einträge) +\nETag für Optimistic Locking

    end

  else COLOR_ERROR ja

    note over eDiag_FA
      List.emptyReason kann den Wert "notstarted" oder 
      "nilknown" haben.

      TODO: Abklären, ob List mit "notstarted" persistiert wird.
    end note

    eDiag_FA --> GDA_1: Collection-Bundle (List ohne Einträge) +\nETag für Optimistic Locking

  end
else COLOR_ERROR Keine Liste vorhanden
  
  eDiag_FA -> eDiag_FA: Leere Liste mit List.emptyReason = notstarted erzeugen
  eDiag_FA --> GDA_1: Collection-Bundle (List ohne Einträge) +\nETag für Optimistic Locking
  deactivate eDiag_FA

end

deactivate GDA_1

@enduml